#!/usr/bin/env Rscript
# ==============================================================================
# Figure 3 Assembly: Global and Local Transcriptomic Effects of Inv4m
# ==============================================================================
#
# This script assembles individual panel PNGs into the final Figure 3 composite.
# Each panel is generated by upstream Rmd scripts and saved to the panels/ directory.
#
# Panel layout (8 panels, A-H):
#
#   +---------+---------+
#   |    A    |    D    |
#   +---------+---------+
#   |    B    |    E    |
#   +---------+---------+
#   |    C    |    F    |
#   +---------+---------+
#   |         |    G    |
#   |         +---------+
#   |         |    H    |
#   +---------+---------+
#
# Column 1: A (Leaf sampling), B (MDS), C (Volcano)
# Column 2: D (Manhattan Leaf), E (Manhattan Inv4m), F (Haplotype), G (Local Manhattan), H (Local logFC)
#
# Usage:
#   Rscript scripts/inversion_paper/assemble_figure3_RNAseq.R
#
# Dependencies:
#   - cowplot, magick, ggplot2, grid, png
#   - Panel PNGs in results/inversion_paper/figures/panels/
#
# Output:
#   - docs/inversion_paper/figs/RNAseq.png (final figure)
#
# ==============================================================================

# Setup ------------------------------------------------------------------------
library(here)
library(cowplot)
library(magick)
library(grid)
library(png)
library(ggplot2)

source(here("scripts", "utils", "setup_paths.R"))
paths <- setup_project_paths("inversion_paper")

# Configuration ----------------------------------------------------------------

# Panel directory
panel_dir <- file.path(paths$figures, "panels")

# Output directory (create figs/ for LaTeX)
output_dir <- here("docs", "inversion_paper", "figs")
if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

# Final figure dimensions (2-column width for journal)
# Nature/Science: ~180mm width, Cell: ~174mm
fig_width_mm <- 180
fig_height_mm <- 200  # Adjust based on actual panel proportions
dpi <- 300

# Convert mm to inches for ggsave
fig_width_in <- fig_width_mm / 25.4
fig_height_in <- fig_height_mm / 25.4

# Panel file paths -------------------------------------------------------------
panel_files <- list(
  A = file.path(panel_dir, "panel_A_leaf_sampling.png"),
  B = file.path(panel_dir, "panel_B_MDS.png"),
  C = file.path(panel_dir, "panel_C_volcano.png"),
  D = file.path(panel_dir, "panel_D_manhattan_leaf.png"),
  E = file.path(panel_dir, "panel_E_manhattan_inv4m.png"),
  F = file.path(panel_dir, "panel_F_haplotype.png"),
  G = file.path(panel_dir, "panel_G_local_manhattan.png"),
  H = file.path(panel_dir, "panel_H_local_logfc.png")
)

# Check which panels exist -----------------------------------------------------
cat("Checking panel availability:\n")
panel_status <- sapply(panel_files, file.exists)
for (p in names(panel_status)) {
  status <- if (panel_status[p]) "OK" else "MISSING"
  cat(sprintf("  Panel %s: %s\n", p, status))
}

if (!all(panel_status)) {
  missing <- names(panel_status)[!panel_status]
  warning(sprintf("Missing panels: %s\nUsing placeholders.",
                  paste(missing, collapse = ", ")))
}

# Helper function: Load panel or create placeholder ----------------------------
load_panel <- function(filepath, label) {
  if (file.exists(filepath)) {
    # Load PNG and convert to ggplot grob
    img <- image_read(filepath)
    grob <- rasterGrob(img, interpolate = TRUE)
    p <- ggdraw() + draw_grob(grob)
  } else {
    # Create placeholder with label
    p <- ggplot() +
      annotate("text", x = 0.5, y = 0.5, label = paste("Panel", label, "\n(missing)"),
               size = 8, color = "gray50") +
      theme_void() +
      theme(
        panel.background = element_rect(fill = "gray95", color = "gray80"),
        plot.margin = margin(5, 5, 5, 5)
      )
  }
  return(p)
}

# Load all panels --------------------------------------------------------------
cat("\nLoading panels...\n")
panels <- lapply(names(panel_files), function(label) {
  load_panel(panel_files[[label]], label)
})
names(panels) <- names(panel_files)

# Add panel labels (A, B, C, etc.) ---------------------------------------------
add_label <- function(plot, label, fontface = "bold", size = 14) {
  ggdraw(plot) +
    draw_label(label, x = 0.02, y = 0.98, hjust = 0, vjust = 1,
               fontface = fontface, size = size)
}

panels_labeled <- mapply(add_label, panels, names(panels), SIMPLIFY = FALSE)

# Assemble figure using cowplot ------------------------------------------------
cat("Assembling figure...\n")

# Column 1: A, B, C (equally spaced, 1/3 each)
col1 <- plot_grid(
  panels_labeled$A,
  panels_labeled$B,
  panels_labeled$C,
  ncol = 1,
  rel_heights = c(1, 1, 1),  # Equal heights (1/3 each)
  align = "v",
  axis = "lr"
)

# Column 2: D, E, F, G, H (stacked vertically)
# D, E are shorter (Manhattan plots); F, G, H are taller (haplotype, local views)
col2 <- plot_grid(
  panels_labeled$D,
  panels_labeled$E,
  panels_labeled$F,
  panels_labeled$G,
  panels_labeled$H,
  ncol = 1,
  rel_heights = c(0.8, 0.8, 1.2, 1.2, 1.2),  # D,E shorter; F,G,H taller
  align = "v",
  axis = "lr"
)

# Combine columns side by side
figure3 <- plot_grid(
  col1,
  col2,
  ncol = 2,
  rel_widths = c(1, 1),  # Equal column widths, adjust if needed
  align = "h",
  axis = "tb"
)

# Save final figure ------------------------------------------------------------
output_file <- file.path(output_dir, "RNAseq.png")

ggsave(
  output_file,
  plot = figure3,
  width = fig_width_in,
  height = fig_height_in,
  dpi = dpi,
  bg = "white"
)

cat(sprintf("\nFigure saved to: %s\n", output_file))
cat(sprintf("Dimensions: %.0f x %.0f mm at %d DPI\n", fig_width_mm, fig_height_mm, dpi))

# Also save as PDF for vector elements -----------------------------------------
# Note: This won't help with rasterized Manhattan plots, but useful for labels
pdf_file <- file.path(output_dir, "RNAseq.pdf")
ggsave(
  pdf_file,
  plot = figure3,
  width = fig_width_in,
  height = fig_height_in,
  device = cairo_pdf
)
cat(sprintf("PDF version saved to: %s\n", pdf_file))

# Summary ----------------------------------------------------------------------
cat("\n=== Assembly Complete ===\n")
cat("Panels used:\n")
for (p in names(panel_status)) {
  src <- if (panel_status[p]) basename(panel_files[[p]]) else "(placeholder)"
  cat(sprintf("  %s: %s\n", p, src))
}

cat("\nTo update panels, run the source scripts:\n")
cat("  1. differential_expression_leaf_treatment_model.Rmd -> Panels B, C, D, E, G, H\n")
cat("  2. plot_genotype_get_correlated_loci.Rmd -> Panel F (haplotype)\n")
cat("  3. Create Panel A manually or with simple ggplot code\n")
